import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/providers/storeProvider";
import { AuthTokenProvider } from "@/providers/authprovider";
import { ApolloWrapper } from "@/config/graphql/config"

export const metadata: Metadata = {
  title: "Gamification Module",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <AuthTokenProvider>
            <ApolloWrapper >
              {children}
            </ApolloWrapper>
          </AuthTokenProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
